name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Run the action when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to PythonAnywhere
        env:
          PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          PYTHONANYWHERE_PASSWORD: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
        run: |
          sshpass -p $PYTHONANYWHERE_PASSWORD ssh -o StrictHostKeyChecking=no $PYTHONANYWHERE_USERNAME@ssh.pythonanywhere.com << 'EOF'
            cd /home/yourusername/yourrepo
            git pull origin main
            source /home/yourusername/yourenv/bin/activate
            pip install -r requirements.txt
            touch /home/yourusername/yourproject.wsgi  # Restart web app
          EOF